# Generated by Django 5.1.6 on 2026-03-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='text',
            field=models.TextField(max_length=10000),
        ),
    ]
